export const SAVECATEGORYID = 'savecategoryid'
export const ADDSHOPTOCART = 'addshoptocart'
export const DELSHOP = 'delshop'
export const CHANGEBUYCHOSEN = 'changebuychosen'
export const CHANGELOGIN = 'changelogin'